class CFG:
    competition='PPPM'
    debug=False
    apex=True
    print_freq=100
    num_workers=4
    model="microsoft/deberta-v3-large"
    scheduler='cosine' # ['linear', 'cosine']
    batch_scheduler=True
    num_cycles=0.5
    num_warmup_steps=0
    epochs=6
    encoder_lr=1e-5
    decoder_lr=1e-5
    min_lr=1e-8
    eps=1e-8
    betas=(0.9, 0.999)
    batch_size=16
    fc_dropout=0.4
    target_size=1
    max_len=512
    weight_decay=0.05
    gradient_accumulation_steps=1
    max_grad_norm=1000
    seed=99
    n_fold=4
    trn_fold=[0, 1, 2, 3]
    train=True
    adv_type = ''
    
